// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/ducconit/tiktok-live-platform/backend/db"
	mock "github.com/stretchr/testify/mock"
)

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, q
func (_m *MockAPIKeyRepository) Count(ctx context.Context, q string) (int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, q)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockAPIKeyRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - q string
func (_e *MockAPIKeyRepository_Expecter) Count(ctx interface{}, q interface{}) *MockAPIKeyRepository_Count_Call {
	return &MockAPIKeyRepository_Count_Call{Call: _e.mock.On("Count", ctx, q)}
}

func (_c *MockAPIKeyRepository_Count_Call) Run(run func(ctx context.Context, q string)) *MockAPIKeyRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Count_Call) Return(_a0 int64, _a1 error) *MockAPIKeyRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_Count_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockAPIKeyRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockAPIKeyRepository) Create(ctx context.Context, p db.CreateAPIKeyParams) (db.ApiKey, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 db.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAPIKeyParams) (db.ApiKey, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAPIKeyParams) db.ApiKey); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(db.ApiKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateAPIKeyParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.CreateAPIKeyParams
func (_e *MockAPIKeyRepository_Expecter) Create(ctx interface{}, p interface{}) *MockAPIKeyRepository_Create_Call {
	return &MockAPIKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockAPIKeyRepository_Create_Call) Run(run func(ctx context.Context, p db.CreateAPIKeyParams)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateAPIKeyParams))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) Return(_a0 db.ApiKey, _a1 error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) RunAndReturn(run func(context.Context, db.CreateAPIKeyParams) (db.ApiKey, error)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, hash
func (_m *MockAPIKeyRepository) GetByHash(ctx context.Context, hash string) (db.ApiKey, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 db.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.ApiKey, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.ApiKey); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Get(0).(db.ApiKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockAPIKeyRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockAPIKeyRepository_Expecter) GetByHash(ctx interface{}, hash interface{}) *MockAPIKeyRepository_GetByHash_Call {
	return &MockAPIKeyRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, hash)}
}

func (_c *MockAPIKeyRepository_GetByHash_Call) Run(run func(ctx context.Context, hash string)) *MockAPIKeyRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByHash_Call) Return(_a0 db.ApiKey, _a1 error) *MockAPIKeyRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (db.ApiKey, error)) *MockAPIKeyRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAPIKeyRepository) GetByID(ctx context.Context, id string) (db.ApiKey, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 db.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.ApiKey, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.ApiKey); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.ApiKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAPIKeyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIKeyRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAPIKeyRepository_GetByID_Call {
	return &MockAPIKeyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAPIKeyRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockAPIKeyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByID_Call) Return(_a0 db.ApiKey, _a1 error) *MockAPIKeyRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (db.ApiKey, error)) *MockAPIKeyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, p
func (_m *MockAPIKeyRepository) List(ctx context.Context, p db.ListAPIKeysParams) ([]db.ApiKey, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListAPIKeysParams) ([]db.ApiKey, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListAPIKeysParams) []db.ApiKey); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ApiKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListAPIKeysParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAPIKeyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.ListAPIKeysParams
func (_e *MockAPIKeyRepository_Expecter) List(ctx interface{}, p interface{}) *MockAPIKeyRepository_List_Call {
	return &MockAPIKeyRepository_List_Call{Call: _e.mock.On("List", ctx, p)}
}

func (_c *MockAPIKeyRepository_List_Call) Run(run func(ctx context.Context, p db.ListAPIKeysParams)) *MockAPIKeyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListAPIKeysParams))
	})
	return _c
}

func (_c *MockAPIKeyRepository_List_Call) Return(_a0 []db.ApiKey, _a1 error) *MockAPIKeyRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_List_Call) RunAndReturn(run func(context.Context, db.ListAPIKeysParams) ([]db.ApiKey, error)) *MockAPIKeyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id
func (_m *MockAPIKeyRepository) Revoke(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockAPIKeyRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIKeyRepository_Expecter) Revoke(ctx interface{}, id interface{}) *MockAPIKeyRepository_Revoke_Call {
	return &MockAPIKeyRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockAPIKeyRepository_Revoke_Call) Run(run func(ctx context.Context, id string)) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Revoke_Call) Return(_a0 error) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_Revoke_Call) RunAndReturn(run func(context.Context, string) error) *MockAPIKeyRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// TouchLastUsed provides a mock function with given fields: ctx, id
func (_m *MockAPIKeyRepository) TouchLastUsed(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for TouchLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_TouchLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchLastUsed'
type MockAPIKeyRepository_TouchLastUsed_Call struct {
	*mock.Call
}

// TouchLastUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIKeyRepository_Expecter) TouchLastUsed(ctx interface{}, id interface{}) *MockAPIKeyRepository_TouchLastUsed_Call {
	return &MockAPIKeyRepository_TouchLastUsed_Call{Call: _e.mock.On("TouchLastUsed", ctx, id)}
}

func (_c *MockAPIKeyRepository_TouchLastUsed_Call) Run(run func(ctx context.Context, id string)) *MockAPIKeyRepository_TouchLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_TouchLastUsed_Call) Return(_a0 error) *MockAPIKeyRepository_TouchLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_TouchLastUsed_Call) RunAndReturn(run func(context.Context, string) error) *MockAPIKeyRepository_TouchLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockAPIKeyRepository) Update(ctx context.Context, p db.UpdateAPIKeyParams) (db.ApiKey, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 db.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAPIKeyParams) (db.ApiKey, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAPIKeyParams) db.ApiKey); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(db.ApiKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateAPIKeyParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAPIKeyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.UpdateAPIKeyParams
func (_e *MockAPIKeyRepository_Expecter) Update(ctx interface{}, p interface{}) *MockAPIKeyRepository_Update_Call {
	return &MockAPIKeyRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockAPIKeyRepository_Update_Call) Run(run func(ctx context.Context, p db.UpdateAPIKeyParams)) *MockAPIKeyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateAPIKeyParams))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Update_Call) Return(_a0 db.ApiKey, _a1 error) *MockAPIKeyRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_Update_Call) RunAndReturn(run func(context.Context, db.UpdateAPIKeyParams) (db.ApiKey, error)) *MockAPIKeyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
