// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/ducconit/tiktok-live-platform/backend/db"
	mock "github.com/stretchr/testify/mock"
)

// MockRBACReader is an autogenerated mock type for the RBACReader type
type MockRBACReader struct {
	mock.Mock
}

type MockRBACReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRBACReader) EXPECT() *MockRBACReader_Expecter {
	return &MockRBACReader_Expecter{mock: &_m.Mock}
}

// GetUserPermissions provides a mock function with given fields: ctx, userID
func (_m *MockRBACReader) GetUserPermissions(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRBACReader_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type MockRBACReader_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRBACReader_Expecter) GetUserPermissions(ctx interface{}, userID interface{}) *MockRBACReader_GetUserPermissions_Call {
	return &MockRBACReader_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, userID)}
}

func (_c *MockRBACReader_GetUserPermissions_Call) Run(run func(ctx context.Context, userID string)) *MockRBACReader_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRBACReader_GetUserPermissions_Call) Return(_a0 []string, _a1 error) *MockRBACReader_GetUserPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRBACReader_GetUserPermissions_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockRBACReader_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function with given fields: ctx, userID
func (_m *MockRBACReader) GetUserRoles(ctx context.Context, userID string) ([]db.Role, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []db.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]db.Role, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []db.Role); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRBACReader_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type MockRBACReader_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRBACReader_Expecter) GetUserRoles(ctx interface{}, userID interface{}) *MockRBACReader_GetUserRoles_Call {
	return &MockRBACReader_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", ctx, userID)}
}

func (_c *MockRBACReader_GetUserRoles_Call) Run(run func(ctx context.Context, userID string)) *MockRBACReader_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRBACReader_GetUserRoles_Call) Return(_a0 []db.Role, _a1 error) *MockRBACReader_GetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRBACReader_GetUserRoles_Call) RunAndReturn(run func(context.Context, string) ([]db.Role, error)) *MockRBACReader_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRBACReader creates a new instance of MockRBACReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRBACReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRBACReader {
	mock := &MockRBACReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
