// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/ducconit/tiktok-live-platform/backend/db"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, p
func (_m *MockRepository) Count(ctx context.Context, p db.CountUsersParams) (int64, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CountUsersParams) (int64, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CountUsersParams) int64); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CountUsersParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.CountUsersParams
func (_e *MockRepository_Expecter) Count(ctx interface{}, p interface{}) *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count", ctx, p)}
}

func (_c *MockRepository_Count_Call) Run(run func(ctx context.Context, p db.CountUsersParams)) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CountUsersParams))
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(_a0 int64, _a1 error) *MockRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func(context.Context, db.CountUsersParams) (int64, error)) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByRole provides a mock function with given fields: ctx, slugs
func (_m *MockRepository) CountByRole(ctx context.Context, slugs []string) (int64, error) {
	ret := _m.Called(ctx, slugs)

	if len(ret) == 0 {
		panic("no return value specified for CountByRole")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (int64, error)); ok {
		return rf(ctx, slugs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) int64); ok {
		r0 = rf(ctx, slugs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, slugs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountByRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByRole'
type MockRepository_CountByRole_Call struct {
	*mock.Call
}

// CountByRole is a helper method to define mock.On call
//   - ctx context.Context
//   - slugs []string
func (_e *MockRepository_Expecter) CountByRole(ctx interface{}, slugs interface{}) *MockRepository_CountByRole_Call {
	return &MockRepository_CountByRole_Call{Call: _e.mock.On("CountByRole", ctx, slugs)}
}

func (_c *MockRepository_CountByRole_Call) Run(run func(ctx context.Context, slugs []string)) *MockRepository_CountByRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRepository_CountByRole_Call) Return(_a0 int64, _a1 error) *MockRepository_CountByRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountByRole_Call) RunAndReturn(run func(context.Context, []string) (int64, error)) *MockRepository_CountByRole_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockRepository) Create(ctx context.Context, p db.CreateUserParams) (db.User, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.CreateUserParams
func (_e *MockRepository_Expecter) Create(ctx interface{}, p interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, p db.CreateUserParams)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 db.User, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.User, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetByEmail(ctx context.Context, email string) (db.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockRepository_GetByEmail_Call {
	return &MockRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByEmail_Call) Return(_a0 db.User, _a1 error) *MockRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *MockRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id string) (db.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 db.User, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, p
func (_m *MockRepository) List(ctx context.Context, p db.ListUsersParams) ([]db.User, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListUsersParams) ([]db.User, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListUsersParams) []db.User); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListUsersParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.ListUsersParams
func (_e *MockRepository_Expecter) List(ctx interface{}, p interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, p)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, p db.ListUsersParams)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListUsersParams))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []db.User, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, db.ListUsersParams) ([]db.User, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRole provides a mock function with given fields: ctx, slugs, pageLimit, pageOffset
func (_m *MockRepository) ListByRole(ctx context.Context, slugs []string, pageLimit int32, pageOffset int32) ([]db.User, error) {
	ret := _m.Called(ctx, slugs, pageLimit, pageOffset)

	if len(ret) == 0 {
		panic("no return value specified for ListByRole")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int32, int32) ([]db.User, error)); ok {
		return rf(ctx, slugs, pageLimit, pageOffset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, int32, int32) []db.User); ok {
		r0 = rf(ctx, slugs, pageLimit, pageOffset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, int32, int32) error); ok {
		r1 = rf(ctx, slugs, pageLimit, pageOffset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRole'
type MockRepository_ListByRole_Call struct {
	*mock.Call
}

// ListByRole is a helper method to define mock.On call
//   - ctx context.Context
//   - slugs []string
//   - pageLimit int32
//   - pageOffset int32
func (_e *MockRepository_Expecter) ListByRole(ctx interface{}, slugs interface{}, pageLimit interface{}, pageOffset interface{}) *MockRepository_ListByRole_Call {
	return &MockRepository_ListByRole_Call{Call: _e.mock.On("ListByRole", ctx, slugs, pageLimit, pageOffset)}
}

func (_c *MockRepository_ListByRole_Call) Run(run func(ctx context.Context, slugs []string, pageLimit int32, pageOffset int32)) *MockRepository_ListByRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *MockRepository_ListByRole_Call) Return(_a0 []db.User, _a1 error) *MockRepository_ListByRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByRole_Call) RunAndReturn(run func(context.Context, []string, int32, int32) ([]db.User, error)) *MockRepository_ListByRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetVerified provides a mock function with given fields: ctx, id
func (_m *MockRepository) SetVerified(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_SetVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVerified'
type MockRepository_SetVerified_Call struct {
	*mock.Call
}

// SetVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) SetVerified(ctx interface{}, id interface{}) *MockRepository_SetVerified_Call {
	return &MockRepository_SetVerified_Call{Call: _e.mock.On("SetVerified", ctx, id)}
}

func (_c *MockRepository_SetVerified_Call) Run(run func(ctx context.Context, id string)) *MockRepository_SetVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_SetVerified_Call) Return(_a0 error) *MockRepository_SetVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_SetVerified_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_SetVerified_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockRepository) Update(ctx context.Context, p db.UpdateUserParams) (db.User, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) (db.User, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) db.User); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateUserParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.UpdateUserParams
func (_e *MockRepository_Expecter) Update(ctx interface{}, p interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, p db.UpdateUserParams)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserParams))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 db.User, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, db.UpdateUserParams) (db.User, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAvatarURL provides a mock function with given fields: ctx, id, url
func (_m *MockRepository) UpdateAvatarURL(ctx context.Context, id string, url string) (db.User, error) {
	ret := _m.Called(ctx, id, url)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatarURL")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (db.User, error)); ok {
		return rf(ctx, id, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) db.User); ok {
		r0 = rf(ctx, id, url)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateAvatarURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAvatarURL'
type MockRepository_UpdateAvatarURL_Call struct {
	*mock.Call
}

// UpdateAvatarURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - url string
func (_e *MockRepository_Expecter) UpdateAvatarURL(ctx interface{}, id interface{}, url interface{}) *MockRepository_UpdateAvatarURL_Call {
	return &MockRepository_UpdateAvatarURL_Call{Call: _e.mock.On("UpdateAvatarURL", ctx, id, url)}
}

func (_c *MockRepository_UpdateAvatarURL_Call) Run(run func(ctx context.Context, id string, url string)) *MockRepository_UpdateAvatarURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateAvatarURL_Call) Return(_a0 db.User, _a1 error) *MockRepository_UpdateAvatarURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateAvatarURL_Call) RunAndReturn(run func(context.Context, string, string) (db.User, error)) *MockRepository_UpdateAvatarURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastLogin provides a mock function with given fields: ctx, id
func (_m *MockRepository) UpdateLastLogin(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateLastLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastLogin'
type MockRepository_UpdateLastLogin_Call struct {
	*mock.Call
}

// UpdateLastLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) UpdateLastLogin(ctx interface{}, id interface{}) *MockRepository_UpdateLastLogin_Call {
	return &MockRepository_UpdateLastLogin_Call{Call: _e.mock.On("UpdateLastLogin", ctx, id)}
}

func (_c *MockRepository_UpdateLastLogin_Call) Run(run func(ctx context.Context, id string)) *MockRepository_UpdateLastLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateLastLogin_Call) Return(_a0 error) *MockRepository_UpdateLastLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateLastLogin_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_UpdateLastLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateName provides a mock function with given fields: ctx, id, fullName
func (_m *MockRepository) UpdateName(ctx context.Context, id string, fullName string) (db.User, error) {
	ret := _m.Called(ctx, id, fullName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateName")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (db.User, error)); ok {
		return rf(ctx, id, fullName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) db.User); ok {
		r0 = rf(ctx, id, fullName)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, fullName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateName'
type MockRepository_UpdateName_Call struct {
	*mock.Call
}

// UpdateName is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - fullName string
func (_e *MockRepository_Expecter) UpdateName(ctx interface{}, id interface{}, fullName interface{}) *MockRepository_UpdateName_Call {
	return &MockRepository_UpdateName_Call{Call: _e.mock.On("UpdateName", ctx, id, fullName)}
}

func (_c *MockRepository_UpdateName_Call) Run(run func(ctx context.Context, id string, fullName string)) *MockRepository_UpdateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpdateName_Call) Return(_a0 db.User, _a1 error) *MockRepository_UpdateName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateName_Call) RunAndReturn(run func(context.Context, string, string) (db.User, error)) *MockRepository_UpdateName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, id, hash
func (_m *MockRepository) UpdatePassword(ctx context.Context, id string, hash string) error {
	ret := _m.Called(ctx, id, hash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - hash string
func (_e *MockRepository_Expecter) UpdatePassword(ctx interface{}, id interface{}, hash interface{}) *MockRepository_UpdatePassword_Call {
	return &MockRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, hash)}
}

func (_c *MockRepository_UpdatePassword_Call) Run(run func(ctx context.Context, id string, hash string)) *MockRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_UpdatePassword_Call) Return(_a0 error) *MockRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
