// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/ducconit/tiktok-live-platform/backend/db"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenStore is an autogenerated mock type for the TokenStore type
type MockTokenStore struct {
	mock.Mock
}

type MockTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStore) EXPECT() *MockTokenStore_Expecter {
	return &MockTokenStore_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function with given fields: ctx, p
func (_m *MockTokenStore) CreateRefreshToken(ctx context.Context, p db.CreateRefreshTokenParams) (db.RefreshToken, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 db.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRefreshTokenParams) (db.RefreshToken, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRefreshTokenParams) db.RefreshToken); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(db.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateRefreshTokenParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockTokenStore_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.CreateRefreshTokenParams
func (_e *MockTokenStore_Expecter) CreateRefreshToken(ctx interface{}, p interface{}) *MockTokenStore_CreateRefreshToken_Call {
	return &MockTokenStore_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, p)}
}

func (_c *MockTokenStore_CreateRefreshToken_Call) Run(run func(ctx context.Context, p db.CreateRefreshTokenParams)) *MockTokenStore_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRefreshTokenParams))
	})
	return _c
}

func (_c *MockTokenStore_CreateRefreshToken_Call) Return(_a0 db.RefreshToken, _a1 error) *MockTokenStore_CreateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_CreateRefreshToken_Call) RunAndReturn(run func(context.Context, db.CreateRefreshTokenParams) (db.RefreshToken, error)) *MockTokenStore_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByHash provides a mock function with given fields: ctx, hash
func (_m *MockTokenStore) GetRefreshTokenByHash(ctx context.Context, hash string) (db.RefreshToken, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByHash")
	}

	var r0 db.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.RefreshToken, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.RefreshToken); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Get(0).(db.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_GetRefreshTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByHash'
type MockTokenStore_GetRefreshTokenByHash_Call struct {
	*mock.Call
}

// GetRefreshTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockTokenStore_Expecter) GetRefreshTokenByHash(ctx interface{}, hash interface{}) *MockTokenStore_GetRefreshTokenByHash_Call {
	return &MockTokenStore_GetRefreshTokenByHash_Call{Call: _e.mock.On("GetRefreshTokenByHash", ctx, hash)}
}

func (_c *MockTokenStore_GetRefreshTokenByHash_Call) Run(run func(ctx context.Context, hash string)) *MockTokenStore_GetRefreshTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_GetRefreshTokenByHash_Call) Return(_a0 db.RefreshToken, _a1 error) *MockTokenStore_GetRefreshTokenByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_GetRefreshTokenByHash_Call) RunAndReturn(run func(context.Context, string) (db.RefreshToken, error)) *MockTokenStore_GetRefreshTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, id
func (_m *MockTokenStore) RevokeRefreshToken(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockTokenStore_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTokenStore_Expecter) RevokeRefreshToken(ctx interface{}, id interface{}) *MockTokenStore_RevokeRefreshToken_Call {
	return &MockTokenStore_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, id)}
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) Run(run func(ctx context.Context, id string)) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) Return(_a0 error) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeUserRefreshTokens provides a mock function with given fields: ctx, userID
func (_m *MockTokenStore) RevokeUserRefreshTokens(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeUserRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_RevokeUserRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserRefreshTokens'
type MockTokenStore_RevokeUserRefreshTokens_Call struct {
	*mock.Call
}

// RevokeUserRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTokenStore_Expecter) RevokeUserRefreshTokens(ctx interface{}, userID interface{}) *MockTokenStore_RevokeUserRefreshTokens_Call {
	return &MockTokenStore_RevokeUserRefreshTokens_Call{Call: _e.mock.On("RevokeUserRefreshTokens", ctx, userID)}
}

func (_c *MockTokenStore_RevokeUserRefreshTokens_Call) Run(run func(ctx context.Context, userID string)) *MockTokenStore_RevokeUserRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_RevokeUserRefreshTokens_Call) Return(_a0 error) *MockTokenStore_RevokeUserRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_RevokeUserRefreshTokens_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenStore_RevokeUserRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenStore creates a new instance of MockTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStore {
	mock := &MockTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
