// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/ducconit/tiktok-live-platform/backend/db"
	mock "github.com/stretchr/testify/mock"
)

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// AssignUserRole provides a mock function with given fields: ctx, userID, roleID
func (_m *MockRoleRepository) AssignUserRole(ctx context.Context, userID string, roleID string) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for AssignUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_AssignUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignUserRole'
type MockRoleRepository_AssignUserRole_Call struct {
	*mock.Call
}

// AssignUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleID string
func (_e *MockRoleRepository_Expecter) AssignUserRole(ctx interface{}, userID interface{}, roleID interface{}) *MockRoleRepository_AssignUserRole_Call {
	return &MockRoleRepository_AssignUserRole_Call{Call: _e.mock.On("AssignUserRole", ctx, userID, roleID)}
}

func (_c *MockRoleRepository_AssignUserRole_Call) Run(run func(ctx context.Context, userID string, roleID string)) *MockRoleRepository_AssignUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleRepository_AssignUserRole_Call) Return(_a0 error) *MockRoleRepository_AssignUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_AssignUserRole_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoleRepository_AssignUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function with given fields: ctx, p
func (_m *MockRoleRepository) CreateRole(ctx context.Context, p db.CreateRoleParams) (db.Role, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 db.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoleParams) (db.Role, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoleParams) db.Role); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(db.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateRoleParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockRoleRepository_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.CreateRoleParams
func (_e *MockRoleRepository_Expecter) CreateRole(ctx interface{}, p interface{}) *MockRoleRepository_CreateRole_Call {
	return &MockRoleRepository_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, p)}
}

func (_c *MockRoleRepository_CreateRole_Call) Run(run func(ctx context.Context, p db.CreateRoleParams)) *MockRoleRepository_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRoleParams))
	})
	return _c
}

func (_c *MockRoleRepository_CreateRole_Call) Return(_a0 db.Role, _a1 error) *MockRoleRepository_CreateRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_CreateRole_Call) RunAndReturn(run func(context.Context, db.CreateRoleParams) (db.Role, error)) *MockRoleRepository_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) DeleteRole(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockRoleRepository_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) DeleteRole(ctx interface{}, id interface{}) *MockRoleRepository_DeleteRole_Call {
	return &MockRoleRepository_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, id)}
}

func (_c *MockRoleRepository_DeleteRole_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_DeleteRole_Call) Return(_a0 error) *MockRoleRepository_DeleteRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_DeleteRole_Call) RunAndReturn(run func(context.Context, string) error) *MockRoleRepository_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) GetRoleByID(ctx context.Context, id string) (db.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByID")
	}

	var r0 db.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Role); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_GetRoleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleByID'
type MockRoleRepository_GetRoleByID_Call struct {
	*mock.Call
}

// GetRoleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) GetRoleByID(ctx interface{}, id interface{}) *MockRoleRepository_GetRoleByID_Call {
	return &MockRoleRepository_GetRoleByID_Call{Call: _e.mock.On("GetRoleByID", ctx, id)}
}

func (_c *MockRoleRepository_GetRoleByID_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_GetRoleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_GetRoleByID_Call) Return(_a0 db.Role, _a1 error) *MockRoleRepository_GetRoleByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_GetRoleByID_Call) RunAndReturn(run func(context.Context, string) (db.Role, error)) *MockRoleRepository_GetRoleByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermissions provides a mock function with given fields: ctx
func (_m *MockRoleRepository) ListPermissions(ctx context.Context) ([]db.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []db.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_ListPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermissions'
type MockRoleRepository_ListPermissions_Call struct {
	*mock.Call
}

// ListPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) ListPermissions(ctx interface{}) *MockRoleRepository_ListPermissions_Call {
	return &MockRoleRepository_ListPermissions_Call{Call: _e.mock.On("ListPermissions", ctx)}
}

func (_c *MockRoleRepository_ListPermissions_Call) Run(run func(ctx context.Context)) *MockRoleRepository_ListPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_ListPermissions_Call) Return(_a0 []db.Permission, _a1 error) *MockRoleRepository_ListPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_ListPermissions_Call) RunAndReturn(run func(context.Context) ([]db.Permission, error)) *MockRoleRepository_ListPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRolePermissions provides a mock function with given fields: ctx, roleID
func (_m *MockRoleRepository) ListRolePermissions(ctx context.Context, roleID string) ([]db.Permission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for ListRolePermissions")
	}

	var r0 []db.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]db.Permission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []db.Permission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_ListRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRolePermissions'
type MockRoleRepository_ListRolePermissions_Call struct {
	*mock.Call
}

// ListRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
func (_e *MockRoleRepository_Expecter) ListRolePermissions(ctx interface{}, roleID interface{}) *MockRoleRepository_ListRolePermissions_Call {
	return &MockRoleRepository_ListRolePermissions_Call{Call: _e.mock.On("ListRolePermissions", ctx, roleID)}
}

func (_c *MockRoleRepository_ListRolePermissions_Call) Run(run func(ctx context.Context, roleID string)) *MockRoleRepository_ListRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_ListRolePermissions_Call) Return(_a0 []db.Permission, _a1 error) *MockRoleRepository_ListRolePermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_ListRolePermissions_Call) RunAndReturn(run func(context.Context, string) ([]db.Permission, error)) *MockRoleRepository_ListRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function with given fields: ctx
func (_m *MockRoleRepository) ListRoles(ctx context.Context) ([]db.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []db.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockRoleRepository_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) ListRoles(ctx interface{}) *MockRoleRepository_ListRoles_Call {
	return &MockRoleRepository_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx)}
}

func (_c *MockRoleRepository_ListRoles_Call) Run(run func(ctx context.Context)) *MockRoleRepository_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_ListRoles_Call) Return(_a0 []db.Role, _a1 error) *MockRoleRepository_ListRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_ListRoles_Call) RunAndReturn(run func(context.Context) ([]db.Role, error)) *MockRoleRepository_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserRole provides a mock function with given fields: ctx, userID, roleID
func (_m *MockRoleRepository) RemoveUserRole(ctx context.Context, userID string, roleID string) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_RemoveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserRole'
type MockRoleRepository_RemoveUserRole_Call struct {
	*mock.Call
}

// RemoveUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - roleID string
func (_e *MockRoleRepository_Expecter) RemoveUserRole(ctx interface{}, userID interface{}, roleID interface{}) *MockRoleRepository_RemoveUserRole_Call {
	return &MockRoleRepository_RemoveUserRole_Call{Call: _e.mock.On("RemoveUserRole", ctx, userID, roleID)}
}

func (_c *MockRoleRepository_RemoveUserRole_Call) Run(run func(ctx context.Context, userID string, roleID string)) *MockRoleRepository_RemoveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleRepository_RemoveUserRole_Call) Return(_a0 error) *MockRoleRepository_RemoveUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_RemoveUserRole_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoleRepository_RemoveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetRolePermissions provides a mock function with given fields: ctx, roleID, permissionIDs
func (_m *MockRoleRepository) SetRolePermissions(ctx context.Context, roleID string, permissionIDs []string) error {
	ret := _m.Called(ctx, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for SetRolePermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_SetRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRolePermissions'
type MockRoleRepository_SetRolePermissions_Call struct {
	*mock.Call
}

// SetRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - permissionIDs []string
func (_e *MockRoleRepository_Expecter) SetRolePermissions(ctx interface{}, roleID interface{}, permissionIDs interface{}) *MockRoleRepository_SetRolePermissions_Call {
	return &MockRoleRepository_SetRolePermissions_Call{Call: _e.mock.On("SetRolePermissions", ctx, roleID, permissionIDs)}
}

func (_c *MockRoleRepository_SetRolePermissions_Call) Run(run func(ctx context.Context, roleID string, permissionIDs []string)) *MockRoleRepository_SetRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockRoleRepository_SetRolePermissions_Call) Return(_a0 error) *MockRoleRepository_SetRolePermissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_SetRolePermissions_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockRoleRepository_SetRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, p
func (_m *MockRoleRepository) UpdateRole(ctx context.Context, p db.UpdateRoleParams) (db.Role, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 db.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoleParams) (db.Role, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoleParams) db.Role); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(db.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateRoleParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockRoleRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - p db.UpdateRoleParams
func (_e *MockRoleRepository_Expecter) UpdateRole(ctx interface{}, p interface{}) *MockRoleRepository_UpdateRole_Call {
	return &MockRoleRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, p)}
}

func (_c *MockRoleRepository_UpdateRole_Call) Run(run func(ctx context.Context, p db.UpdateRoleParams)) *MockRoleRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateRoleParams))
	})
	return _c
}

func (_c *MockRoleRepository_UpdateRole_Call) Return(_a0 db.Role, _a1 error) *MockRoleRepository_UpdateRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_UpdateRole_Call) RunAndReturn(run func(context.Context, db.UpdateRoleParams) (db.Role, error)) *MockRoleRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
