// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"time"
)

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT COUNT(*) FROM api_keys
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountAPIKeys(ctx context.Context, q_ string) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeys, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_hash, key_prefix, scopes, expires_at, is_active, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, key_hash, key_prefix, scopes, expires_at, is_active, last_used_at, created_by, revoked_at, created_at, updated_at
`

type CreateAPIKeyParams struct {
	Name      string     `json:"name"`
	KeyHash   string     `json:"key_hash"`
	KeyPrefix string     `json:"key_prefix"`
	Scopes    []string   `json:"scopes"`
	ExpiresAt *time.Time `json:"expires_at"`
	IsActive  bool       `json:"is_active"`
	CreatedBy *string    `json:"created_by"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.ExpiresAt,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, key_hash, key_prefix, scopes, expires_at, is_active, last_used_at, created_by, revoked_at, created_at, updated_at FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, key_hash, key_prefix, scopes, expires_at, is_active, last_used_at, created_by, revoked_at, created_at, updated_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_hash, key_prefix, scopes, expires_at, is_active, last_used_at, created_by, revoked_at, created_at, updated_at FROM api_keys
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAPIKeysParams struct {
	Q          string `json:"q"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scopes,
			&i.ExpiresAt,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET is_active = FALSE, revoked_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys
SET name = $2, scopes = $3, expires_at = $4, is_active = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, key_hash, key_prefix, scopes, expires_at, is_active, last_used_at, created_by, revoked_at, created_at, updated_at
`

type UpdateAPIKeyParams struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Scopes    []string   `json:"scopes"`
	ExpiresAt *time.Time `json:"expires_at"`
	IsActive  bool       `json:"is_active"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKey,
		arg.ID,
		arg.Name,
		arg.Scopes,
		arg.ExpiresAt,
		arg.IsActive,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
