// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
	"time"
)

const deleteExpiredIdempotency = `-- name: DeleteExpiredIdempotency :exec
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotency(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotency)
	return err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT key, method, path, request_hash, response_status, response_body, created_at, expires_at FROM idempotency_keys WHERE key = $1 AND expires_at > now()
`

func (q *Queries) GetIdempotency(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotency, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :one
INSERT INTO idempotency_keys (key, method, path, request_hash, response_status, response_body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (key) DO NOTHING
RETURNING key, method, path, request_hash, response_status, response_body, created_at, expires_at
`

type InsertIdempotencyParams struct {
	Key            string    `json:"key"`
	Method         string    `json:"method"`
	Path           string    `json:"path"`
	RequestHash    string    `json:"request_hash"`
	ResponseStatus int32     `json:"response_status"`
	ResponseBody   string    `json:"response_body"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotency,
		arg.Key,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
