// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CountAPIKeys(ctx context.Context, q_ string) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountUsersActive(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, slugs []string) (int64, error)
	CountUsersRecent(ctx context.Context) ([]CountUsersRecentRow, error)
	// ============ Stats cho admin dashboard ============
	CountUsersTotal(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// ============ Refresh tokens ============
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredIdempotency(ctx context.Context) error
	DeleteRole(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error)
	GetIdempotency(ctx context.Context, key string) (IdempotencyKey, error)
	GetPermissionBySlug(ctx context.Context, slug string) (Permission, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserPermissions(ctx context.Context, userID string) ([]string, error)
	// ============ RBAC ============
	GetUserRoles(ctx context.Context, userID string) ([]Role, error)
	InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) (IdempotencyKey, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error)
	// ============ Permissions ============
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRolePermissions(ctx context.Context, roleID string) ([]Permission, error)
	// ============ Roles ============
	ListRoles(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	RevokeAPIKey(ctx context.Context, id string) error
	RevokeRefreshToken(ctx context.Context, id string) error
	RevokeUserRefreshTokens(ctx context.Context, userID string) error
	RoleDistribution(ctx context.Context) ([]RoleDistributionRow, error)
	SetEmailVerified(ctx context.Context, id string) error
	SetRolePermissions(ctx context.Context, arg SetRolePermissionsParams) error
	TouchAPIKeyLastUsed(ctx context.Context, id string) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error)
	UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) (User, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
