// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
	"time"
)

const countUsersActive = `-- name: CountUsersActive :one
SELECT COUNT(*) FROM users WHERE is_active = TRUE
`

func (q *Queries) CountUsersActive(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersRecent = `-- name: CountUsersRecent :many
SELECT date_trunc('day', created_at)::date AS day, COUNT(*) AS count
FROM users
WHERE created_at >= now() - interval '30 days'
GROUP BY day
ORDER BY day
`

type CountUsersRecentRow struct {
	Day   time.Time `json:"day"`
	Count int64     `json:"count"`
}

func (q *Queries) CountUsersRecent(ctx context.Context) ([]CountUsersRecentRow, error) {
	rows, err := q.db.Query(ctx, countUsersRecent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUsersRecentRow
	for rows.Next() {
		var i CountUsersRecentRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsersTotal = `-- name: CountUsersTotal :one

SELECT COUNT(*) FROM users
`

// ============ Stats cho admin dashboard ============
func (q *Queries) CountUsersTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const roleDistribution = `-- name: RoleDistribution :many
SELECT r.id, COUNT(ur.user_id) AS count
FROM roles r
LEFT JOIN user_roles ur ON ur.role_id = r.id
GROUP BY r.id
ORDER BY count DESC
`

type RoleDistributionRow struct {
	ID    string `json:"id"`
	Count int64  `json:"count"`
}

func (q *Queries) RoleDistribution(ctx context.Context) ([]RoleDistributionRow, error) {
	rows, err := q.db.Query(ctx, roleDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleDistributionRow
	for rows.Next() {
		var i RoleDistributionRow
		if err := rows.Scan(&i.ID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
